apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oexm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0082-tenant/ci10t-776-0082-app/devfile-sample-oexm@sha256:a172b17aa0c68334e60b95390d1a3ce59980d679678af7ff1598081f42f1fe23
        name: my-nodejs
        resources: {}
status: {}
